// G1 Turf Analytics — Japanese G1 racing dataset
// All historical data sourced from public JRA records.

const G1_RACES = [
  // 春シーズン (Spring)
  { id: 'feb',   name: 'フェブラリーS',   nameEn: 'February Stakes',     month: 2,  day: 16, course: '東京', distance: 1600, surface: 'ダート', dir: '左', established: 1984 },
  { id: 'taka',  name: '高松宮記念',       nameEn: 'Takamatsunomiya Kinen', month: 3, day: 22, course: '中京', distance: 1200, surface: '芝',     dir: '左', established: 1971 },
  { id: 'osa',   name: '大阪杯',           nameEn: 'Osaka Hai',           month: 4,  day: 5,  course: '阪神', distance: 2000, surface: '芝',     dir: '右', established: 1957 },
  { id: 'oka',   name: '桜花賞',           nameEn: 'Oka Sho',             month: 4,  day: 12, course: '阪神', distance: 1600, surface: '芝',     dir: '右', established: 1939 },
  { id: 'sat',   name: '皐月賞',           nameEn: 'Satsuki Sho',         month: 4,  day: 19, course: '中山', distance: 2000, surface: '芝',     dir: '右', established: 1939 },
  { id: 'ten1',  name: '天皇賞（春）',     nameEn: 'Tenno Sho (Spring)',  month: 5,  day: 3,  course: '京都', distance: 3200, surface: '芝',     dir: '右', established: 1937 },
  { id: 'nhk',   name: 'NHKマイルC',       nameEn: 'NHK Mile Cup',        month: 5,  day: 10, course: '東京', distance: 1600, surface: '芝',     dir: '左', established: 1996 },
  { id: 'vic',   name: 'ヴィクトリアM',   nameEn: 'Victoria Mile',       month: 5,  day: 17, course: '東京', distance: 1600, surface: '芝',     dir: '左', established: 2006 },
  { id: 'oaks',  name: '優駿牝馬（オークス）', nameEn: 'Yushun Himba',    month: 5,  day: 24, course: '東京', distance: 2400, surface: '芝',     dir: '左', established: 1938 },
  { id: 'derby', name: '東京優駿（日本ダービー）', nameEn: 'Tokyo Yushun', month: 5, day: 31, course: '東京', distance: 2400, surface: '芝',     dir: '左', established: 1932 },
  { id: 'yas',   name: '安田記念',         nameEn: 'Yasuda Kinen',        month: 6,  day: 7,  course: '東京', distance: 1600, surface: '芝',     dir: '左', established: 1951 },
  { id: 'tak',   name: '宝塚記念',         nameEn: 'Takarazuka Kinen',    month: 6,  day: 28, course: '阪神', distance: 2200, surface: '芝',     dir: '右', established: 1960 },
  // 夏 (Summer)
  { id: 'sprS',  name: 'スプリンターズS', nameEn: 'Sprinters Stakes',    month: 9,  day: 27, course: '中山', distance: 1200, surface: '芝',     dir: '右', established: 1967 },
  // 秋シーズン (Autumn)
  { id: 'shu',   name: '秋華賞',           nameEn: 'Shuka Sho',           month: 10, day: 18, course: '京都', distance: 2000, surface: '芝',     dir: '右', established: 1996 },
  { id: 'kik',   name: '菊花賞',           nameEn: 'Kikuka Sho',          month: 10, day: 25, course: '京都', distance: 3000, surface: '芝',     dir: '右', established: 1938 },
  { id: 'ten2',  name: '天皇賞（秋）',     nameEn: 'Tenno Sho (Autumn)',  month: 11, day: 1,  course: '東京', distance: 2000, surface: '芝',     dir: '左', established: 1937 },
  { id: 'efs',   name: 'エリザベス女王杯', nameEn: 'Queen Elizabeth II Cup', month: 11, day: 15, course: '京都', distance: 2200, surface: '芝',  dir: '右', established: 1976 },
  { id: 'mile',  name: 'マイルCS',         nameEn: 'Mile Championship',   month: 11, day: 22, course: '京都', distance: 1600, surface: '芝',     dir: '右', established: 1984 },
  { id: 'jpc',   name: 'ジャパンC',        nameEn: 'Japan Cup',           month: 11, day: 29, course: '東京', distance: 2400, surface: '芝',     dir: '左', established: 1981 },
  { id: 'cha',   name: 'チャンピオンズC', nameEn: 'Champions Cup',       month: 12, day: 6,  course: '中京', distance: 1800, surface: 'ダート', dir: '左', established: 2014 },
  { id: 'has',   name: '阪神JF',           nameEn: 'Hanshin JF',          month: 12, day: 13, course: '阪神', distance: 1600, surface: '芝',     dir: '右', established: 1949 },
  { id: 'asa',   name: '朝日杯FS',         nameEn: 'Asahi Hai FS',        month: 12, day: 20, course: '阪神', distance: 1600, surface: '芝',     dir: '右', established: 1949 },
  { id: 'arima', name: '有馬記念',         nameEn: 'Arima Kinen',         month: 12, day: 28, course: '中山', distance: 2500, surface: '芝',     dir: '右', established: 1956 },
  { id: 'hop',   name: 'ホープフルS',     nameEn: 'Hopeful Stakes',      month: 12, day: 29, course: '中山', distance: 2000, surface: '芝',     dir: '右', established: 2014 },
];

// 過去のレース結果サンプル (近年の代表的なG1結果)
const PAST_RESULTS = {
  derby: [
    { year: 2025, results: [
      { rank: 1, horse: 'クロワデュノール',  jockey: '北村友一',    time: '2:23.7', odds: 3.2 },
      { rank: 2, horse: 'マスカレードボール', jockey: '横山武史',    time: '2:23.8', odds: 8.5 },
      { rank: 3, horse: 'サトノシャイニング', jockey: 'モレイラ',    time: '2:23.9', odds: 12.4 },
    ]},
    { year: 2024, results: [
      { rank: 1, horse: 'ダノンデサイル',     jockey: '横山典弘',    time: '2:24.3', odds: 11.6 },
      { rank: 2, horse: 'ジャスティンミラノ', jockey: '戸崎圭太',    time: '2:24.4', odds: 1.9 },
      { rank: 3, horse: 'シンエンペラー',     jockey: '坂井瑠星',    time: '2:24.6', odds: 5.5 },
    ]},
    { year: 2023, results: [
      { rank: 1, horse: 'タスティエーラ',     jockey: 'レーン',      time: '2:25.2', odds: 6.4 },
      { rank: 2, horse: 'ソールオリエンス',   jockey: '横山武史',    time: '2:25.2', odds: 1.7 },
      { rank: 3, horse: 'ハーツコンチェルト', jockey: '松山弘平',    time: '2:25.4', odds: 24.7 },
    ]},
    { year: 2022, results: [
      { rank: 1, horse: 'ドウデュース',       jockey: '武豊',        time: '2:21.9', odds: 3.2 },
      { rank: 2, horse: 'イクイノックス',     jockey: 'ルメール',    time: '2:22.0', odds: 2.3 },
      { rank: 3, horse: 'アスクビクターモア', jockey: '田辺裕信',    time: '2:22.2', odds: 17.9 },
    ]},
    { year: 2021, results: [
      { rank: 1, horse: 'シャフリヤール',     jockey: '福永祐一',    time: '2:22.5', odds: 6.6 },
      { rank: 2, horse: 'エフフォーリア',     jockey: '横山武史',    time: '2:22.5', odds: 2.3 },
      { rank: 3, horse: 'ステラヴェローチェ', jockey: '吉田隼人',    time: '2:23.0', odds: 19.3 },
    ]},
  ],
  arima: [
    { year: 2024, results: [
      { rank: 1, horse: 'レガレイラ',         jockey: '戸崎圭太',    time: '2:30.4', odds: 6.5 },
      { rank: 2, horse: 'シャフリヤール',     jockey: 'モレイラ',    time: '2:30.5', odds: 5.7 },
      { rank: 3, horse: 'ジャスティンパレス', jockey: 'ルメール',    time: '2:30.6', odds: 4.0 },
    ]},
    { year: 2023, results: [
      { rank: 1, horse: 'ドウデュース',       jockey: '武豊',        time: '2:30.9', odds: 4.0 },
      { rank: 2, horse: 'スターズオンアース', jockey: 'ルメール',    time: '2:31.0', odds: 4.6 },
      { rank: 3, horse: 'タスティエーラ',     jockey: 'モレイラ',    time: '2:31.0', odds: 7.6 },
    ]},
    { year: 2022, results: [
      { rank: 1, horse: 'イクイノックス',     jockey: 'ルメール',    time: '2:32.4', odds: 2.3 },
      { rank: 2, horse: 'ボルドグフーシュ',   jockey: '福永祐一',    time: '2:32.5', odds: 36.3 },
      { rank: 3, horse: 'ジェラルディーナ',   jockey: '武豊',        time: '2:32.5', odds: 7.5 },
    ]},
  ],
  jpc: [
    { year: 2024, results: [
      { rank: 1, horse: 'ドウデュース',       jockey: '武豊',        time: '2:21.0', odds: 1.6 },
      { rank: 2, horse: 'シンエンペラー',     jockey: 'マーフィー',  time: '2:21.4', odds: 11.4 },
      { rank: 3, horse: 'スターズオンアース', jockey: 'モレイラ',    time: '2:21.5', odds: 5.2 },
    ]},
    { year: 2023, results: [
      { rank: 1, horse: 'イクイノックス',     jockey: 'ルメール',    time: '2:21.8', odds: 1.4 },
      { rank: 2, horse: 'リバティアイランド', jockey: '川田将雅',    time: '2:22.4', odds: 3.4 },
      { rank: 3, horse: 'スターズオンアース', jockey: 'ビュイック',  time: '2:22.6', odds: 7.2 },
    ]},
  ],
  ten1: [
    { year: 2025, results: [
      { rank: 1, horse: 'ヘデントール',       jockey: 'ルメール',    time: '3:14.8', odds: 4.1 },
      { rank: 2, horse: 'ショウナンラプンタ', jockey: '横山典弘',    time: '3:14.9', odds: 18.6 },
      { rank: 3, horse: 'サンライズアース',   jockey: '池添謙一',    time: '3:14.9', odds: 9.8 },
    ]},
    { year: 2024, results: [
      { rank: 1, horse: 'テーオーロイヤル',   jockey: '菱田裕二',    time: '3:14.4', odds: 8.6 },
      { rank: 2, horse: 'ブローザホーン',     jockey: '菅原明良',    time: '3:14.6', odds: 6.3 },
      { rank: 3, horse: 'ディープボンド',     jockey: '幸英明',      time: '3:14.6', odds: 6.7 },
    ]},
  ],
  oaks: [
    { year: 2024, results: [
      { rank: 1, horse: 'チェルヴィニア',     jockey: 'ルメール',    time: '2:24.0', odds: 5.0 },
      { rank: 2, horse: 'ステレンボッシュ',   jockey: 'モレイラ',    time: '2:24.1', odds: 2.4 },
      { rank: 3, horse: 'ライトバック',       jockey: '坂井瑠星',    time: '2:24.1', odds: 5.5 },
    ]},
    { year: 2023, results: [
      { rank: 1, horse: 'リバティアイランド', jockey: '川田将雅',    time: '2:23.1', odds: 1.4 },
      { rank: 2, horse: 'ハーパー',           jockey: 'ルメール',    time: '2:23.7', odds: 6.4 },
      { rank: 3, horse: 'ドゥーラ',           jockey: '斎藤新',      time: '2:24.0', odds: 73.0 },
    ]},
  ],
  vic: [
    { year: 2025, results: [
      { rank: 1, horse: 'アスコリピチェーノ', jockey: 'ルメール',    time: '1:30.9', odds: 2.7 },
      { rank: 2, horse: 'ラビュリンス',       jockey: '北村宏司',    time: '1:31.2', odds: 96.7 },
      { rank: 3, horse: 'ボンドガール',       jockey: '横山武史',    time: '1:31.2', odds: 8.4 },
    ]},
    { year: 2024, results: [
      { rank: 1, horse: 'テンハッピーローズ', jockey: '津村明秀',    time: '1:31.8', odds: 137.5 },
      { rank: 2, horse: 'フィアスプライド',   jockey: 'ルメール',    time: '1:31.8', odds: 22.7 },
      { rank: 3, horse: 'マスクトディーヴァ', jockey: '松山弘平',    time: '1:31.8', odds: 4.5 },
    ]},
  ],
};

// 名馬データベース
const LEGENDARY_HORSES = [
  {
    id: 'equinox',
    name: 'イクイノックス',
    nameEn: 'Equinox',
    sex: '牡',
    born: 2019,
    sire: 'キタサンブラック',
    dam: 'シャトーブランシュ',
    damSire: 'キングヘイロー',
    trainer: '木村哲也',
    owner: 'シルクレーシング',
    starts: 10, wins: 8, place2: 2, place3: 0,
    earnings: 2227595900,
    g1Wins: 6,
    tags: ['年度代表馬', 'ワールドベスト', '世界1位レーティング'],
    bio: '通算10戦8勝で引退。レーティング世界1位を獲得し、ジャパンC・有馬記念・天皇賞秋・宝塚記念・ドバイシーマC・天皇賞秋を制覇。2022・2023年連続で年度代表馬。',
    grades: { speed: 99, stamina: 95, power: 96, dirt: 50, mental: 98 },
    races: [
      { year: 2023, race: 'ジャパンC',     rank: 1 },
      { year: 2023, race: '天皇賞（秋）', rank: 1 },
      { year: 2023, race: '宝塚記念',     rank: 1 },
      { year: 2023, race: 'ドバイシーマC', rank: 1 },
      { year: 2022, race: '有馬記念',     rank: 1 },
      { year: 2022, race: '天皇賞（秋）', rank: 1 },
      { year: 2022, race: '日本ダービー', rank: 2 },
      { year: 2022, race: '皐月賞',       rank: 2 },
    ],
  },
  {
    id: 'douduce',
    name: 'ドウデュース',
    nameEn: 'Do Deuce',
    sex: '牡',
    born: 2019,
    sire: 'ハーツクライ',
    dam: 'ダストアンドダイヤモンズ',
    damSire: 'Vindication',
    trainer: '友道康夫',
    owner: 'キーファーズ',
    starts: 15, wins: 7, place2: 1, place3: 2,
    earnings: 1816776300,
    g1Wins: 5,
    tags: ['ダービー馬', '武豊伝説', '凱旋門出走'],
    bio: '武豊騎手と共に日本ダービー・ジャパンC・有馬記念・天皇賞秋を制覇。武豊にとって6度目のダービー制覇。引退後はキーファーズが大事に管理。',
    grades: { speed: 94, stamina: 96, power: 90, dirt: 45, mental: 95 },
    races: [
      { year: 2024, race: 'ジャパンC',     rank: 1 },
      { year: 2024, race: '天皇賞（秋）', rank: 1 },
      { year: 2023, race: '有馬記念',     rank: 1 },
      { year: 2022, race: '日本ダービー', rank: 1 },
      { year: 2021, race: '朝日杯FS',     rank: 1 },
    ],
  },
  {
    id: 'liberty',
    name: 'リバティアイランド',
    nameEn: 'Liberty Island',
    sex: '牝',
    born: 2020,
    sire: 'ドゥラメンテ',
    dam: 'ヤンキーローズ',
    damSire: 'All American',
    trainer: '中内田充正',
    owner: 'サンデーレーシング',
    starts: 9, wins: 5, place2: 2, place3: 0,
    earnings: 938510000,
    g1Wins: 4,
    tags: ['三冠牝馬', '怪物', '最優秀3歳牝馬'],
    bio: '2023年牝馬三冠（桜花賞・オークス・秋華賞）達成。ジャパンCで古馬を相手に2着、最強牝馬の評価を確立。',
    grades: { speed: 96, stamina: 92, power: 88, dirt: 40, mental: 90 },
    races: [
      { year: 2023, race: '秋華賞',       rank: 1 },
      { year: 2023, race: 'オークス',     rank: 1 },
      { year: 2023, race: '桜花賞',       rank: 1 },
      { year: 2023, race: 'ジャパンC',   rank: 2 },
      { year: 2022, race: '阪神JF',       rank: 1 },
    ],
  },
  {
    id: 'almond',
    name: 'アーモンドアイ',
    nameEn: 'Almond Eye',
    sex: '牝',
    born: 2015,
    sire: 'ロードカナロア',
    dam: 'フサイチパンドラ',
    damSire: 'サンデーサイレンス',
    trainer: '国枝栄',
    owner: 'シルクレーシング',
    starts: 15, wins: 11, place2: 2, place3: 1,
    earnings: 1919126300,
    g1Wins: 9,
    tags: ['三冠牝馬', 'G1史上最多9勝', '年度代表馬2回'],
    bio: 'JRAのG1最多9勝。三冠＋ジャパンC2回＋天皇賞秋2回＋ドバイ＋ヴィクトリアM。3歳でジャパンCをレコード勝ち。',
    grades: { speed: 99, stamina: 90, power: 92, dirt: 50, mental: 96 },
    races: [
      { year: 2020, race: 'ジャパンC',     rank: 1 },
      { year: 2020, race: '天皇賞（秋）', rank: 1 },
      { year: 2020, race: 'ヴィクトリアM', rank: 1 },
      { year: 2019, race: '天皇賞（秋）', rank: 1 },
      { year: 2019, race: 'ドバイターフ', rank: 1 },
      { year: 2018, race: 'ジャパンC',     rank: 1 },
      { year: 2018, race: '秋華賞',       rank: 1 },
      { year: 2018, race: 'オークス',     rank: 1 },
      { year: 2018, race: '桜花賞',       rank: 1 },
    ],
  },
  {
    id: 'kitasan',
    name: 'キタサンブラック',
    nameEn: 'Kitasan Black',
    sex: '牡',
    born: 2012,
    sire: 'ブラックタイド',
    dam: 'シュガーハート',
    damSire: 'サクラバクシンオー',
    trainer: '清水久詞',
    owner: '北島三郎',
    starts: 20, wins: 12, place2: 2, place3: 4,
    earnings: 1876843000,
    g1Wins: 7,
    tags: ['年度代表馬', '逃げ馬', '父サンデー系'],
    bio: '北島三郎オーナーの代表馬。菊花賞・天皇賞春2回・天皇賞秋・ジャパンC・大阪杯・有馬記念を制覇。引退後イクイノックスを輩出。',
    grades: { speed: 88, stamina: 99, power: 91, dirt: 55, mental: 94 },
    races: [
      { year: 2017, race: '有馬記念',     rank: 1 },
      { year: 2017, race: 'ジャパンC',   rank: 1 },
      { year: 2017, race: '天皇賞（春）', rank: 1 },
      { year: 2017, race: '大阪杯',       rank: 1 },
      { year: 2016, race: '天皇賞（秋）', rank: 1 },
      { year: 2016, race: '天皇賞（春）', rank: 1 },
      { year: 2015, race: '菊花賞',       rank: 1 },
    ],
  },
  {
    id: 'orfevre',
    name: 'オルフェーヴル',
    nameEn: 'Orfevre',
    sex: '牡',
    born: 2008,
    sire: 'ステイゴールド',
    dam: 'オリエンタルアート',
    damSire: 'メジロマックイーン',
    trainer: '池江泰寿',
    owner: 'サンデーレーシング',
    starts: 21, wins: 12, place2: 6, place3: 0,
    earnings: 1576100400,
    g1Wins: 6,
    tags: ['三冠馬', '凱旋門2着', '気性難'],
    bio: '2011年三冠馬。凱旋門賞2年連続2着。有馬記念2勝。気性難で知られるも世界レベルで活躍。',
    grades: { speed: 94, stamina: 97, power: 95, dirt: 60, mental: 75 },
    races: [
      { year: 2013, race: '有馬記念',     rank: 1 },
      { year: 2013, race: '宝塚記念',     rank: 1 },
      { year: 2012, race: '宝塚記念',     rank: 1 },
      { year: 2011, race: '有馬記念',     rank: 1 },
      { year: 2011, race: '菊花賞',       rank: 1 },
      { year: 2011, race: '日本ダービー', rank: 1 },
      { year: 2011, race: '皐月賞',       rank: 1 },
    ],
  },
  {
    id: 'deep',
    name: 'ディープインパクト',
    nameEn: 'Deep Impact',
    sex: '牡',
    born: 2002,
    sire: 'サンデーサイレンス',
    dam: 'ウインドインハーヘア',
    damSire: 'Alzao',
    trainer: '池江泰郎',
    owner: '金子真人',
    starts: 14, wins: 12, place2: 1, place3: 0,
    earnings: 1454555000,
    g1Wins: 7,
    tags: ['三冠馬', '無敗', '伝説の種牡馬'],
    bio: '無敗の三冠馬。生涯14戦12勝。引退後は日本競馬史上最高の種牡馬となり、コントレイル等多数のG1馬を輩出。',
    grades: { speed: 99, stamina: 98, power: 96, dirt: 55, mental: 92 },
    races: [
      { year: 2006, race: '有馬記念',     rank: 1 },
      { year: 2006, race: 'ジャパンC',   rank: 1 },
      { year: 2006, race: '天皇賞（春）', rank: 1 },
      { year: 2006, race: '宝塚記念',     rank: 1 },
      { year: 2005, race: '菊花賞',       rank: 1 },
      { year: 2005, race: '日本ダービー', rank: 1 },
      { year: 2005, race: '皐月賞',       rank: 1 },
    ],
  },
  {
    id: 'thauzin',
    name: 'シンボリルドルフ',
    nameEn: 'Symboli Rudolf',
    sex: '牡',
    born: 1981,
    sire: 'パーソロン',
    dam: 'スイートルナ',
    damSire: 'スピードシンボリ',
    trainer: '野平祐二',
    owner: 'シンボリ牧場',
    starts: 16, wins: 13, place2: 1, place3: 1,
    earnings: 684482000,
    g1Wins: 7,
    tags: ['七冠馬', '皇帝', '初の無敗三冠'],
    bio: '皇帝の異名を持つ。史上初の無敗三冠馬で、史上初のJRA七冠を達成。',
    grades: { speed: 95, stamina: 97, power: 96, dirt: 60, mental: 99 },
    races: [
      { year: 1986, race: '有馬記念',     rank: 1 },
      { year: 1985, race: '天皇賞（春）', rank: 1 },
      { year: 1985, race: 'ジャパンC',   rank: 1 },
      { year: 1985, race: '有馬記念',     rank: 1 },
      { year: 1984, race: '菊花賞',       rank: 1 },
      { year: 1984, race: '日本ダービー', rank: 1 },
      { year: 1984, race: '皐月賞',       rank: 1 },
    ],
  },
];

// 騎手スタッツ (2025年データ近似)
const JOCKEY_STATS = [
  { name: 'C.ルメール',  g1Wins: 47, winRate: 24.8, plRate: 49.5, country: '🇫🇷' },
  { name: '川田将雅',    g1Wins: 23, winRate: 23.5, plRate: 46.2, country: '🇯🇵' },
  { name: '武豊',        g1Wins: 84, winRate: 14.2, plRate: 32.8, country: '🇯🇵' },
  { name: '横山武史',    g1Wins: 14, winRate: 17.6, plRate: 38.4, country: '🇯🇵' },
  { name: '戸崎圭太',    g1Wins: 13, winRate: 16.8, plRate: 39.5, country: '🇯🇵' },
  { name: 'モレイラ',    g1Wins: 11, winRate: 26.4, plRate: 50.1, country: '🇧🇷' },
  { name: '坂井瑠星',    g1Wins:  8, winRate: 14.5, plRate: 33.7, country: '🇯🇵' },
  { name: '松山弘平',    g1Wins:  7, winRate: 13.2, plRate: 31.0, country: '🇯🇵' },
];

// 種牡馬スタッツ
const SIRE_STATS = [
  { name: 'ディープインパクト', g1Progeny: 49, totalG1: 84, type: 'SS系' },
  { name: 'キングカメハメハ',   g1Progeny: 35, totalG1: 58, type: 'ミスプロ系' },
  { name: 'ロードカナロア',     g1Progeny: 22, totalG1: 38, type: 'ミスプロ系' },
  { name: 'ハーツクライ',       g1Progeny: 18, totalG1: 31, type: 'SS系' },
  { name: 'ステイゴールド',     g1Progeny: 15, totalG1: 28, type: 'SS系' },
  { name: 'ドゥラメンテ',       g1Progeny: 12, totalG1: 19, type: 'キンカメ系' },
  { name: 'キタサンブラック',   g1Progeny:  8, totalG1: 14, type: 'SS系' },
  { name: 'モーリス',           g1Progeny:  9, totalG1: 13, type: 'ロベルト系' },
];

// 各G1の特徴・傾向データ
const RACE_TRENDS = {
  derby: {
    favoriteWinRate: 32,   // 過去10年で1番人気勝率
    avgWinOdds: 6.8,
    keyTrend: '皐月賞からの臨戦が王道。前走3着以内が好走条件。',
    bias: { '逃げ': 8, '先行': 28, '差し': 45, '追込': 19 },
    keyFactor: ['脚質: 差し有利', '内枠より中枠', '直線の瞬発力'],
  },
  arima: {
    favoriteWinRate: 28,
    avgWinOdds: 8.4,
    keyTrend: 'グランプリ。スタミナと底力勝負。内枠優勢の伝統。',
    bias: { '逃げ': 12, '先行': 32, '差し': 38, '追込': 18 },
    keyFactor: ['内枠有利', '前年好走馬リピート', '中山適性'],
  },
  oaks: {
    favoriteWinRate: 38,
    avgWinOdds: 5.2,
    keyTrend: '桜花賞からの距離延長。母父スタミナ血統に注目。',
    bias: { '逃げ': 6, '先行': 24, '差し': 50, '追込': 20 },
    keyFactor: ['距離延長対応', '桜花賞組優勢', '母系のスタミナ'],
  },
  vic: {
    favoriteWinRate: 25,
    avgWinOdds: 15.6,
    keyTrend: '波乱多発。長期休養明けで巻き返す馬も多い。',
    bias: { '逃げ': 10, '先行': 30, '差し': 42, '追込': 18 },
    keyFactor: ['東京マイル巧者', '前哨戦実績', '高松宮組も注目'],
  },
  ten1: {
    favoriteWinRate: 30,
    avgWinOdds: 7.5,
    keyTrend: '春の盾。3200mのスタミナ勝負。阪神大賞典組に注目。',
    bias: { '逃げ': 10, '先行': 35, '差し': 40, '追込': 15 },
    keyFactor: ['ステイヤー血統', '阪神大賞典上位', '長距離経験'],
  },
  jpc: {
    favoriteWinRate: 42,
    avgWinOdds: 4.8,
    keyTrend: '世界の名馬が集結。日本馬の地力が問われる秋の頂上決戦。',
    bias: { '逃げ': 8, '先行': 30, '差し': 45, '追込': 17 },
    keyFactor: ['東京2400適性', '前哨戦内容', '海外馬輸送ダメージ'],
  },
};

// 実出走馬データ (Web検索ベース、2026/5/17 ヴィクトリアM 第21回)
// 出典: netkeiba/競馬ラボ/Yahoo!競馬/SPREAD/競馬の魅力 等 (2026/5/17 当日朝時点)
//
// 【確定情報】枠順・馬番・馬名・性齢・騎手・斤量(全頭56kg定量)
// 【最新オッズ反映】各馬の想定単勝オッズと人気順(複数ソース統合)
// 【推定情報】脚質・直近3走(競走履歴から推定)
// recent: 直近3走の着順、course: high(勝鞍)/mid(連対)/low(未経験or苦手)
const RACE_ENTRIES = {
  vic: {
    year: 2026,
    note: '2026年ヴィクトリアM 第21回 (5/17東京 G1 15:40発走) — 当日朝の最新予想オッズ反映',
    verified: ['post', 'num', 'name', 'sex', 'age', 'jockey', 'weight'],
    estimated: ['odds', 'popular', 'style', 'recent', 'course'],
    entries: [
      { post: 1, num:  1, name: 'カピリナ',           sex: '牝', age: 5, jockey: '横山典弘',     weight: 56, popular: 16, odds: 85.0, style: '差し', recent: [6, 4, 8], course: 'low'  },
      { post: 1, num:  2, name: 'ワイドラトゥール',   sex: '牝', age: 5, jockey: '横山武史',     weight: 56, popular: 18, odds:110.0, style: '差し', recent: [9, 5, 5], course: 'low'  },
      { post: 2, num:  3, name: 'マピュース',         sex: '牝', age: 4, jockey: 'F.ゴンサルベス', weight: 56, popular: 13, odds: 46.5, style: '追込', recent: [5, 7, 8], course: 'low'  },
      { post: 2, num:  4, name: 'エリカエクスプレス', sex: '牝', age: 4, jockey: '武豊',         weight: 56, popular:  7, odds: 19.5, style: '逃げ', recent: [4, 1, 1], course: 'mid'  },
      { post: 3, num:  5, name: 'ケリフレッドアスク', sex: '牝', age: 4, jockey: 'M.ディー',     weight: 56, popular: 15, odds: 75.0, style: '先行', recent: [3, 6, 5], course: 'mid'  },
      { post: 3, num:  6, name: 'ラヴァンダ',         sex: '牝', age: 5, jockey: '岩田望来',     weight: 56, popular: 11, odds: 32.0, style: '差し', recent: [3, 2, 5], course: 'mid'  },
      { post: 4, num:  7, name: 'クイーンズウォーク', sex: '牝', age: 5, jockey: '西村淳也',     weight: 56, popular:  3, odds:  8.0, style: '差し', recent: [3, 2, 1], course: 'high' },
      { post: 4, num:  8, name: 'カムニャック',       sex: '牝', age: 4, jockey: '川田将雅',     weight: 56, popular:  2, odds:  5.0, style: '先行', recent: [2, 1, 1], course: 'mid'  },
      { post: 5, num:  9, name: 'ココナッツブラウン', sex: '牝', age: 6, jockey: '北村友一',     weight: 56, popular: 10, odds: 25.0, style: '差し', recent: [5, 4, 7], course: 'mid'  },
      { post: 5, num: 10, name: 'ドロップオブライト', sex: '牝', age: 7, jockey: '松若風馬',     weight: 56, popular: 17, odds: 95.0, style: '差し', recent: [4, 5, 7], course: 'mid'  },
      { post: 6, num: 11, name: 'ボンドガール',       sex: '牝', age: 5, jockey: '丹内祐次',     weight: 56, popular: 14, odds: 55.0, style: '差し', recent: [5, 2, 6], course: 'mid'  },
      { post: 6, num: 12, name: 'エンブロイダリー',   sex: '牝', age: 4, jockey: 'C.ルメール',   weight: 56, popular:  1, odds:  2.5, style: '先行', recent: [1, 1, 1], course: 'mid'  },
      { post: 7, num: 13, name: 'カナテープ',         sex: '牝', age: 7, jockey: '松山弘平',     weight: 56, popular:  9, odds: 24.0, style: '差し', recent: [7, 6, 8], course: 'low'  },
      { post: 7, num: 14, name: 'ジョスラン',         sex: '牝', age: 4, jockey: '戸崎圭太',     weight: 56, popular:  4, odds: 12.5, style: '差し', recent: [3, 4, 5], course: 'mid'  },
      { post: 7, num: 15, name: 'アイサンサン',       sex: '牝', age: 4, jockey: '幸英明',       weight: 56, popular: 12, odds: 40.5, style: '先行', recent: [6, 5, 4], course: 'low'  },
      { post: 8, num: 16, name: 'ニシノティアモ',     sex: '牝', age: 5, jockey: '津村明秀',     weight: 56, popular:  6, odds: 19.0, style: '先行', recent: [4, 3, 5], course: 'mid'  },
      { post: 8, num: 17, name: 'パラディレーヌ',     sex: '牝', age: 4, jockey: '坂井瑠星',     weight: 56, popular:  8, odds: 22.5, style: '差し', recent: [2, 3, 6], course: 'mid'  },
      { post: 8, num: 18, name: 'チェルヴィニア',     sex: '牝', age: 5, jockey: 'D.レーン',     weight: 56, popular:  5, odds: 15.0, style: '差し', recent: [5, 7, 4], course: 'high' },
    ],
  },
  derby: {
    year: 2026,
    note: '2026年日本ダービー 想定登録メンバー（プリセット）',
    entries: [
      { post: 1, num:  2, name: 'サンプルダービー1', sex: '牡', age: 3, jockey: 'C.ルメール',  weight: 57, popular: 1, odds: 3.2, style: '差し', recent: [1, 2, 1], course: 'mid' },
      { post: 2, num:  5, name: 'サンプルダービー2', sex: '牡', age: 3, jockey: '川田将雅',    weight: 57, popular: 2, odds: 4.8, style: '先行', recent: [1, 1, 3], course: 'high' },
      { post: 3, num:  8, name: 'サンプルダービー3', sex: '牡', age: 3, jockey: 'モレイラ',    weight: 57, popular: 3, odds: 6.5, style: '差し', recent: [2, 1, 5], course: 'mid' },
    ],
  },
};

// 騎手名 → スタッツ高速ルックアップ
const JOCKEY_MAP = Object.fromEntries(JOCKEY_STATS.map(j => [j.name, j]));

window.G1_DATA = {
  races: G1_RACES,
  pastResults: PAST_RESULTS,
  horses: LEGENDARY_HORSES,
  jockeys: JOCKEY_STATS,
  jockeyMap: JOCKEY_MAP,
  sires: SIRE_STATS,
  trends: RACE_TRENDS,
  entries: RACE_ENTRIES,
};
